import type { Metadata } from "next";
import NavBar from './components/NavBar';
import "./globals.css";
import { Cairo, Tajawal, Noto_Sans_Arabic } from 'next/font/google'

const cairo = Cairo({ subsets: ['arabic'], weight: ['400','600','700'], display: 'swap' })
const tajawal = Tajawal({ subsets: ['arabic'], weight: ['400','500','700','800'], display: 'swap' })
const noto_sans_arabic = Noto_Sans_Arabic({ subsets: ['arabic'], weight: ['400','700'], display: 'swap' })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ar">
      <body
        className={cairo.className}
      >
      <NavBar />
        {children}
      </body>
    </html>
  );
}
